### PR TITLE
Make ModelState Error Prefix Optional

### PR DESCRIPTION
**Pull request by RehanSaeed**

### CODE REVIEW

**Comment by JeremySkinner** [comment]
Hi @RehanSaeed I believe making parameters optional is actually a binary breaking change so this isn't something I'll be able to merge without a major version release. Can you switch this to be a separate overload instead? We can then switch it to an optional parameter on the next major release. 

Edit: I misremembered - it's adding a *new* optional parameter that's problematic, but this is an existing parameter so should be fine. I'll aim to merge later this week.

**Comment by RehanSaeed** [comment]
Makes sense, I wasn't sure how amenable you'd be to a breaking change.

Added an overload now. This may also be slightly better for performance since there is no null or empty check.

**Comment by JeremySkinner** [comment]
thanks!

**Comment by JeremySkinner** [comment]
I've pushed out 11.2.2 with this change

**Pull request merged**
